### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kerrywatson1**
Updates to documentation instructions.

### CODE REVIEW

**Comment by kerrywatson1** [comment]
@asmeurer please review and merge.

**Comment by asmeurer** [comment]
@kerrywatson1 you made this pull request incorrectly (and [this one](https://github.com/kerrywatson1/conda-docs/pull/2) too). You have this as a pull request from your fork to your fork. It needs to be from your fork to conda/conda-docs. Basically, when you create the pull request, it needs to look like this 
screen shot 2015-05-18 at 1 08 49 pm. I have gone ahead and done it correctly for this branch at https://github.com/conda/conda-docs/pull/50 and the other one at https://github.com/conda/conda-docs/pull/51. 

I spoke with @electronwill last Friday on a good git workflow for you guys. You should sync up with him and let me know if you have any questions.

**Comment by kerrywatson1** [comment]
Thanks Aaron, these are docs I did before you did the good git workflow for
us, I'm trying to patch them up and get them out of here. Thanks for your
patience. Kerry

**Comment by kerrywatson1** [comment]
@asmeurer cleaning up docs and closing this request.

**Pull request closed without merging**
